// <auto-generated />
namespace SiscomSoft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Coke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Coke));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211958229_Coke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
